with src as (
    select * from {{ ref('base_apif__fixture_players') }}
)

select
    {{ dbt_utils.generate_surrogate_key(['fixture_id', 'league_code', 'team_id', 'player_id']) }}
        as fixture_player_stat_sk,
    cast(fixture_id as int64) as fixture_sk,
    cast(team_id as int64) as team_sk,
    cast(player_id as int64) as player_sk,
    league_code,
    fixture_id as fixture_api_id,
    team_id as team_api_id,
    player_id as player_api_id,
    minutes,
    shirt_number,
    position_code,
    is_captain,
    is_substitute,
    coalesce(minutes, 0) > 0 and not coalesce(is_substitute, false) as is_starter,
    offsides,
    shots,
    shots_on_target,
    goals,
    goals_penalty,
    goals_against,
    assists,
    saves,
    passes,
    passes_key,
    passes_accurate,
    tackles,
    blocks,
    interceptions,
    duels,
    duels_won,
    dribbles,
    dribbles_success,
    dribbles_against,
    fouls,
    fouls_against,
    cards_yellow,
    cards_red,
    penalties_won,
    penalties_committed,
    penalties_scored,
    penalties_missed,
    penalties_saved,
    src.raw_ingested_at
from src
