version: 2

sources:
  - name: football_data_org
    description: "Raw football-data.org API payloads loaded by Cloud Function."
    schema: FOOTBALL_DATA_ORG
    tables:
      - name: raw_fdorg_teams_bl1
        identifier: RAW_FDORG_TEAMS_BL1
      - name: raw_fdorg_teams_pl
        identifier: RAW_FDORG_TEAMS_PL
      - name: raw_fdorg_teams_sa
        identifier: RAW_FDORG_TEAMS_SA
      - name: raw_fdorg_teams_pd
        identifier: RAW_FDORG_TEAMS_PD
      - name: raw_fdorg_teams_fl1
        identifier: RAW_FDORG_TEAMS_FL1

      - name: raw_fdorg_standings_bl1
        identifier: RAW_FDORG_STANDINGS_BL1
      - name: raw_fdorg_standings_pl
        identifier: RAW_FDORG_STANDINGS_PL
      - name: raw_fdorg_standings_sa
        identifier: RAW_FDORG_STANDINGS_SA
      - name: raw_fdorg_standings_pd
        identifier: RAW_FDORG_STANDINGS_PD
      - name: raw_fdorg_standings_fl1
        identifier: RAW_FDORG_STANDINGS_FL1

      - name: raw_fdorg_matches_scheduled_bl1
        identifier: RAW_FDORG_MATCHES_SCHEDULED_BL1
      - name: raw_fdorg_matches_scheduled_pl
        identifier: RAW_FDORG_MATCHES_SCHEDULED_PL
      - name: raw_fdorg_matches_scheduled_sa
        identifier: RAW_FDORG_MATCHES_SCHEDULED_SA
      - name: raw_fdorg_matches_scheduled_pd
        identifier: RAW_FDORG_MATCHES_SCHEDULED_PD
      - name: raw_fdorg_matches_scheduled_fl1
        identifier: RAW_FDORG_MATCHES_SCHEDULED_FL1
