"""Snapshot the GitLab tracker into the repo — a BACKUP, never a second roadmap.

Writes `docs/tracker/gitlab_snapshot.md`: every milestone and every issue, open and closed,
with its body, grouped by milestone in a deterministic order, fetched through the `glab` login
already on this machine (no token of its own). The header carries the UTC time and a sha256 of
the body; `tests/test_tracker_snapshot.py` recomputes it, so any change the script did not
make fails CI, and `.claude/hooks/tracker_snapshot_gate.py` refuses an Edit or Write to the
folder, so no session can change the file by hand. The file is read only when GitLab is
unreachable — `CLAUDE.md` "Which source answers which question" — and is regenerated at the
end of every session, riding in the handover commit outside the review patch and hash.

Usage: python scripts/snapshot_tracker.py [--project 85168767] [--out docs/tracker/gitlab_snapshot.md]
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import subprocess
import sys
from datetime import datetime, timezone

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DEFAULT_PROJECT = "85168767"
DEFAULT_OUT = os.path.join("docs", "tracker", "gitlab_snapshot.md")

BANNER = (
    "GENERATED by scripts/snapshot_tracker.py — a BACKUP of the GitLab tracker, read only when "
    "GitLab is unreachable, never edited by hand. The GitLab issue is the source of what is "
    "required; this file is what would be restored from."
)


def glab_json(path: str) -> list | dict:
    """One `glab api` GET, decoded as UTF-8 bytes (the console's text mode is cp1252)."""
    r = subprocess.run(["glab", "api", path], capture_output=True)
    if r.returncode != 0:
        sys.exit(f"glab api {path} failed: {r.stderr.decode('utf-8', 'replace')[:300]}")
    return json.loads(r.stdout.decode("utf-8"))


def paginated(project: str, resource: str, query: str = "") -> list[dict]:
    items: list[dict] = []
    page = 1
    while True:
        batch = glab_json(f"projects/{project}/{resource}?per_page=100&page={page}{query}")
        if not batch:
            return items
        items.extend(batch)
        if len(batch) < 100:
            return items
        page += 1


def render(milestones: list[dict], issues: list[dict]) -> str:
    by_ms: dict[int | None, list[dict]] = {}
    for i in issues:
        key = i["milestone"]["id"] if i.get("milestone") else None
        by_ms.setdefault(key, []).append(i)
    for group in by_ms.values():
        group.sort(key=lambda i: i["iid"])

    out: list[str] = []
    out.append("# GitLab tracker snapshot\n")
    out.append(f"{len(milestones)} milestones, {len(issues)} issues "
               f"({sum(1 for i in issues if i['state'] == 'opened')} open, "
               f"{sum(1 for i in issues if i['state'] == 'closed')} closed).\n")

    out.append("## Milestones\n")
    for m in sorted(milestones, key=lambda m: m["title"]):
        out.append(f"- **{m['title']}** ({m['state']}, milestone {m['iid']}): {m.get('description') or ''}".rstrip())
    out.append("")

    ordered = sorted(milestones, key=lambda m: m["title"])
    for m in ordered:
        out.append(f"## {m['title']}\n")
        for i in by_ms.get(m["id"], []):
            out.extend(_issue(i))
    out.append("## No milestone\n")
    for i in by_ms.get(None, []):
        out.extend(_issue(i))
    return "\n".join(out).rstrip() + "\n"


def _issue(i: dict) -> list[str]:
    labels = ", ".join(i.get("labels") or [])
    head = f"### #{i['iid']} {i['title']}"
    meta = (f"_{i['state']} · created {i['created_at'][:10]}"
            + (f" · closed {i['closed_at'][:10]}" if i.get("closed_at") else "")
            + (f" · labels: {labels}" if labels else "") + "_")
    body = (i.get("description") or "").replace("\r\n", "\n").rstrip()
    return [head, "", meta, "", body, ""]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", default=DEFAULT_PROJECT)
    ap.add_argument("--out", default=DEFAULT_OUT)
    a = ap.parse_args()

    milestones = paginated(a.project, "milestones", "&state=all")
    issues = paginated(a.project, "issues", "&state=all&scope=all")
    body = render(milestones, issues)
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header = (f"<!-- {BANNER} -->\n"
              f"<!-- snapshot: {stamp} · sha256(body): {digest} -->\n\n")

    out_path = a.out if os.path.isabs(a.out) else os.path.join(REPO, a.out)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with io.open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + body)
    print(f"wrote {os.path.relpath(out_path, REPO)}: {len(milestones)} milestones, "
          f"{len(issues)} issues, {len(header) + len(body):,} chars, sha256 {digest[:12]}…")
    return 0


if __name__ == "__main__":
    sys.exit(main())
