"""Generate the metric docs blocks from `metric_catalogue.csv`, and check they match.

#82 step 4. The catalogue is this project's only source of what a metric MEANS
(`dbt_project/seeds/schema.yml`: "The single source of truth for every metric we
compute"). The same vocabulary is also 501 columns spread across 11 model ymls,
and until now those columns carried no description at all. Writing them by hand
would have created a second source that drifts from the seed, which is the exact
failure this programme exists to remove — `league_code` reached 76 descriptions in
22 wordings that way.

So the blocks are GENERATED and never authored. Edit the seed; regenerate. The
CPO's 2026-08-21 RULING 3 is the standard being met: "We use docs blocks but only
if we have a mechanism to apply it consistently."

WHY ONE SCRIPT WITH `--check` RATHER THAN A GENERATOR AND A SEPARATE CHECKER, the
`sync_dbt_vars.py` + `check_registry_var_sync.py` shape: two files must each
compute the expected output, and the two copies drift. Here `_render()` is the
single definition of what correct looks like, and both modes call it.

⚠ IT EMITS A BLOCK FOR EVERY METRIC, deliberately, not only for the columns that
happen to be blank today. That keeps the output a pure function of the seed, so a
fresh run reproduces the file byte for byte — the property platform-reviewer
required in MR3, where a name-scoped refusal meant the shipped diff could not be
regenerated by the tool that produced it. The alternative was a hand-maintained
list of metrics to skip, which is the same anti-pattern as an exemption list.

⛔ ONE NAME CAN MEAN TWO THINGS AND THE SCRIPT MUST NOT GUESS. `goals_open_play`
is the authoritative scoreline minus penalties and own goals for a team, and total
goals minus penalties for a player. The catalogue's real key is
`(metric_id, entity)`, not `metric_id`. Where a metric's rows disagree, this emits
one block PER ENTITY (`goals_open_play__team`) so nothing has to pick a winner,
and it ABORTS if it cannot tell the rows apart. Six columns were wired to the
wrong meaning of `league_code` in MR3 by a tool that assumed one name means one
thing; that assumption is not repeated here.

Usage:

    python scripts/sync_metric_docs_blocks.py            # write the file
    python scripts/sync_metric_docs_blocks.py --check    # fail if it has drifted
"""
from __future__ import annotations

import argparse
import csv
import io
import pathlib
import re
import sys
import textwrap

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
SEED = REPO_ROOT / "dbt_project" / "seeds" / "metric_catalogue.csv"

# ⚠ MUST live under `models/`. dbt reads docs blocks from `docs-paths`, which is
# unset in dbt_project.yml and therefore defaults to `models/`. A block outside it
# does not fail loudly — the reference renders as the literal text "{{ doc(...) }}"
# into the warehouse column. `check_description_hygiene.py` restricts its own
# discovery the same way so the gate and dbt cannot disagree.
OUT = REPO_ROOT / "dbt_project" / "models" / "docs" / "metric_columns.md"

# Floor under the read, enforced here and not only in the tests. A renamed column,
# a moved seed or a parser change could leave this matching nothing, and a
# generator that emits an empty file "successfully" would silently delete every
# definition on the next run. Set well under the 76 measured and well over zero.
# Same precedent as `check_description_hygiene.py`'s MIN_DESCRIPTIONS.
MIN_METRICS = 50

# The seed declares itself window-free: "the window and any null policy are applied
# where the metric is computed, never here". 35 descriptions contradicted that and
# were corrected in this MR. This keeps them corrected — a window claim is FALSE on
# a per-match core column, and these blocks are attached to core columns.
#
# ⚠ THE WORD ALONE, not a list of phrasings. An earlier version matched only
# `form window|in the window|same-window` and MISSED `finishing_efficiency`, whose
# text said "share the window" and "the window is not fully shot-covered" — three
# occurrences, none of them on the list. Worse, the MR's own verification searched
# with this same pattern, so it could only ever agree with the guard: a too-narrow
# grep reported as a clean sweep. Caught by football-analytics-expert-reviewer.
# Since the seed declares itself window-free, ANY occurrence is wrong and there is
# no phrasing to enumerate.
WINDOW_PHRASING = re.compile(r"\bwindow\b", re.I)

WRAP = 95

HEADER = """<!--
GENERATED FILE - DO NOT EDIT BY HAND.

Every block below is produced from dbt_project/seeds/metric_catalogue.csv by
scripts/sync_metric_docs_blocks.py. To change a definition, change the seed's
`description` and regenerate; an edit made here is overwritten and, until it is,
makes the seed and the warehouse disagree about what a metric means.

    python scripts/sync_metric_docs_blocks.py

A metric whose team and player rows define it differently gets one block per
entity, suffixed __team / __player, so no caller has to guess which meaning it is
pointing at.
-->
"""


class Abort(Exception):
    """The input is not what this script knows how to read. Never guess."""


def _read_rows() -> list[dict]:
    if not SEED.exists():
        raise Abort("seed not found: " + str(SEED))
    with open(SEED, encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    if len(rows) < MIN_METRICS:
        raise Abort(
            "read only " + str(len(rows)) + " catalogue rows (floor " + str(MIN_METRICS)
            + "). The read has stopped matching - a generator over zero rows would "
            "emit an empty file and delete every definition."
        )
    for r in rows:
        for field in ("metric_id", "entity", "description"):
            if not (r.get(field) or "").strip():
                raise Abort(
                    "row " + repr(r.get("metric_id")) + " has an empty " + field
                    + ". Every metric must define itself; an empty slot here becomes "
                    "an empty description on every column of that name."
                )
    return rows


def _blocks(rows: list[dict]) -> dict[str, str]:
    """Map block name -> definition text.

    One block per metric where its rows agree, one block per entity where they do
    not. Aborts rather than picking a winner.
    """
    by_metric: dict[str, list[dict]] = {}
    for r in rows:
        by_metric.setdefault(r["metric_id"].strip(), []).append(r)

    blocks: dict[str, str] = {}
    for metric, group in by_metric.items():
        texts = {(r["description"] or "").strip() for r in group}
        if len(texts) == 1:
            blocks[metric] = texts.pop()
            continue
        # The rows disagree. Split on entity - but only if entity actually
        # separates them. If two rows share an entity and still disagree, there is
        # no key to split on and guessing would repeat the league_code defect.
        entities = [(r["entity"] or "").strip() for r in group]
        if len(set(entities)) != len(entities):
            raise Abort(
                "metric " + repr(metric) + " has rows that define it differently but "
                "share an entity, so there is no key to tell them apart. Fix the "
                "seed; this script will not choose one."
            )
        for r in group:
            suffix = (r["entity"] or "").strip().replace(" ", "_")
            blocks[metric + "__" + suffix] = (r["description"] or "").strip()
    return blocks


def _render(rows: list[dict]) -> bytes:
    blocks = _blocks(rows)

    offenders = sorted(n for n, t in blocks.items() if WINDOW_PHRASING.search(t))
    if offenders:
        raise Abort(
            "these definitions still describe a window, which is false on a "
            "per-match column and contradicts the seed's own contract: "
            + ", ".join(offenders)
        )

    out = io.StringIO()
    out.write(HEADER)
    for name in sorted(blocks):
        body = "\n".join(textwrap.wrap(blocks[name], width=WRAP)) or blocks[name]
        out.write("\n\n")
        out.write("{% docs " + name + " %}\n")
        out.write(body + "\n")
        out.write("{% enddocs %}\n")

    # ⚠ CRLF to match shared_columns.md and every other tracked file here. Writing
    # LF would rewrite the whole file on the first run and `git diff` would hide
    # it, because it normalises line endings. That has cost a review round before.
    return out.getvalue().replace("\n", "\r\n").encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the file matches the seed. Writes nothing; exits 1 on drift.",
    )
    args = parser.parse_args()

    try:
        rows = _read_rows()
        expected = _render(rows)
    except Abort as exc:
        print("sync_metric_docs_blocks: " + str(exc), file=sys.stderr)
        return 1

    count = expected.count(b"{% docs ")
    current = OUT.read_bytes() if OUT.exists() else None

    if args.check:
        if current is None:
            print("FAIL: " + _rel(OUT) + " does not exist. Run "
                  "`python scripts/sync_metric_docs_blocks.py` to create it.")
            return 1
        if current != expected:
            print("FAIL: " + _rel(OUT) + " has drifted from "
                  + _rel(SEED) + ".\n")
            for line in _describe_drift(current, expected):
                print("  - " + line)
            print("\nThe seed is the source. Do not edit the generated file: run\n"
                  "  python scripts/sync_metric_docs_blocks.py")
            return 1
        print("OK: " + str(count) + " metric docs blocks match " + _rel(SEED) + ".")
        return 0

    if current == expected:
        # Loud, not silently green - the `declare_missing_columns.py` precedent. A
        # generator that reports success while doing nothing is how a broken read
        # passes for a working one.
        print("sync_metric_docs_blocks: already up to date (" + str(count)
              + " blocks). Nothing written.", file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(expected)
    print("WROTE " + _rel(OUT) + ": " + str(count) + " blocks from " + _rel(SEED) + ".")
    return 0


def _rel(path: pathlib.Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT)).replace("\\", "/")
    except ValueError:
        return str(path)


def _describe_drift(current: bytes, expected: bytes) -> list[str]:
    """Name the blocks that differ, so a failure is actionable without a diff tool."""
    def parse(blob: bytes) -> dict[str, str]:
        text = blob.decode("utf-8", errors="replace")
        found = {}
        for m in re.finditer(r"\{%\s*docs\s+(\w+)\s*%\}(.*?)\{%\s*enddocs\s*%\}",
                             text, re.DOTALL):
            found[m.group(1)] = " ".join(m.group(2).split())
        return found

    now, want = parse(current), parse(expected)
    lines = []
    for name in sorted(set(want) - set(now)):
        lines.append("missing block: " + name)
    for name in sorted(set(now) - set(want)):
        lines.append("block no longer in the seed: " + name)
    for name in sorted(set(now) & set(want)):
        if now[name] != want[name]:
            lines.append("changed: " + name)
    if not lines:
        # Same blocks, same text - so the difference is formatting or line endings.
        lines.append(
            "the blocks all match but the bytes do not: formatting, ordering or "
            "line endings differ. Regenerate rather than hand-fixing."
        )
    return lines


if __name__ == "__main__":
    raise SystemExit(main())
